# Generated by Django 3.1.6 on 2021-02-16 17:57

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('ClassRoom_Token', models.CharField(default='LJFdwDKJTjWtKFJGzdPFhgCb1sAXgLeC9adTTRJuF0tiIIX13o', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('ClassRoom_Name', models.CharField(max_length=200)),
                ('ClassRoom_Description', models.TextField(max_length=300)),
                ('ClassRoom_ProfileImage', models.ImageField(upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegisterToken_Token', models.CharField(default='XYMksnlwJ1YqRs2G0IEqmPIFvyGLfqqcxiixuSIX8I1RAeQkJP', max_length=50)),
                ('RegisterToken_Code', models.CharField(default='9eyj84', max_length=50)),
                ('RegisterToken_CreateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_Token', models.CharField(default='qjY18HTpCy6zDyQaYtIOgrk5SLtzLsJmyoiVCxiCTuybfh3Hw3', max_length=100)),
                ('Teacher_Id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Teacher_Password', models.CharField(max_length=100)),
                ('Teacher_Email', models.EmailField(max_length=254)),
                ('Teacher_Name', models.CharField(default='uservgU63PzEC8', max_length=100)),
                ('Teacher_Description', models.TextField(max_length=300)),
                ('Teacher_ProfileImage', models.ImageField(upload_to='Images')),
                ('Teacher_CreatDate', django_jalali.db.models.jDateField(auto_now=True)),
            ],
        ),
    ]
