# Generated by Django 3.1.6 on 2021-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHAT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='ClassRoom_Token',
            field=models.CharField(default='p11GNIOVNl0EloF6LPoeqxOL9Ev6X0JQCwkw0pXcCiZgThxVYp', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='RegisterToken_Code',
            field=models.CharField(default='j59SzJ', max_length=50),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='RegisterToken_Token',
            field=models.CharField(default='hNBrUDa06XxsmIGoRLBgY7odJ74WaI81PCQkkPNpiBgoCL6Ebq', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_Description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_Name',
            field=models.CharField(default='userLQIDU6K9r9', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_ProfileImage',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_Token',
            field=models.CharField(default='KGj2XUWjOR6AHjUKUykAweE6XZN8fCU7XIwSqAUtjyiXQtmfAC', max_length=100),
        ),
    ]
