# Generated by Django 3.1.6 on 2021-02-19 15:51

import KHAT.Permssion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHAT', '0002_auto_20210216_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='ClassRoom_Token',
            field=models.CharField(default=KHAT.Permssion.TeacherToken_Uniq, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='RegisterToken_Code',
            field=models.CharField(default='mead2z', max_length=50),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='RegisterToken_Token',
            field=models.CharField(default='eiZNqvNjNYB5xKuXRiRxuGklCGqOJFryD4J3Tmxn9ks2ZsRyzO', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_Name',
            field=models.CharField(default='userN7ZzWCcSxB', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_Token',
            field=models.CharField(default=KHAT.Permssion.TeacherToken_Uniq, max_length=100),
        ),
    ]
